### ISSUE TITLE
Blank separator name

### ISSUE THREAD

**Issue by hugok79** [thewaiter/separator#5]
After using the Separator module, when right click, I think it would be better to name it `Transparent` instead of `Blank separator`

For instance, I believe that in  Xfce (DE) it's like that....

**Comment by thewaiter** [comment]
good point, thx

**Comment by rbtylee** [comment]
Great Idea! :D I implemented and updated what PO files we had using Google Translate. If that is not good enough, maybe translators can fix it at some point.
